jenkinsci/role-strategy-plugin

src/main/resources/com/michelin/cio/hudson/plugins/rolestrategy/RoleStrategyConfig/assign-global-roles.jelly, src/main/resources/com/michelin/cio/hudson/plugins/rolestrategy/RoleStrategyConfig/assign-project-roles.jelly, src/main/resources/com/michelin/cio/hudson/plugins/rolestrategy/RoleStrategyConfig/assign-slave-roles.jelly, src/main/webapp/help/help-user-group-add.html
Users still try to add groups in Jenkins which are not exactly written in the same way they are using in their Access Control, e.g. LDAP, AD, ... 
Hopefully, some of them will read the help button and will figure out that it is indeed case sensitive and it needs to be written in the same way.
@reviewbybees
=> Add case sensitive help

pom.xml, src/main/java/com/michelin/cio/hudson/plugins/rolestrategy/RoleMap.java, src/test/java/org/jenkinsci/plugins/rolestrategy/RoleAssignmentTest.java, src/test/java/org/jenkinsci/plugins/rolestrategy/UserAuthoritiesAsRolesTest.java, src/test/resources/org/jenkinsci/plugins/rolestrategy/RoleAssignmentTest/testRoleAssignment/config.xml, src/test/resources/org/jenkinsci/plugins/rolestrategy/UserAuthoritiesAsRolesTest/testRoleAuthority/config.xml
This is useful in combination with other plugins, like LDAP Authentication to treat groups as roles.
Also I've added two tests. One covering the basic working flow and another to check if authorities are being treated as roles.
=> Treat user authorities as roles

src/main/java/com/michelin/cio/hudson/plugins/rolestrategy/RoleMap.java
This check suppresses runtime exceptions and prevents failure of the Authorization Strategy, which is fatal for Jenkins.
https://issues.jenkins-ci.org/browse/JENKINS-35652
=> [JENKINS-35652] - Authorities resolution: Catch Runtime Exceptions from the SecurityRealm

src/main/java/com/michelin/cio/hudson/plugins/rolestrategy/RoleBasedAuthorizationStrategy.java, src/main/resources/com/michelin/cio/hudson/plugins/rolestrategy/RoleBasedAuthorizationStrategy/help.html, src/main/resources/com/michelin/cio/hudson/plugins/rolestrategy/RoleStrategyConfig/assign-roles.jelly, src/main/resources/index.jelly, src/main/resources/org/jenkinsci/plugins/rolestrategy/RoleBasedProjectNamingStrategy/help.html
=> Built-in Documentation update

src/main/java/com/michelin/cio/hudson/plugins/rolestrategy/Role.java
I have experienced severe slowdown caused by following stacktrace:
at java.util.AbstractSet.hashCode(AbstractSet.java:126)
at com.michelin.cio.hudson.plugins.rolestrategy.Role.hashCode(Role.java:149)
at java.util.HashMap.hash(HashMap.java:338)
at java.util.HashMap.put(HashMap.java:611)
at java.util.HashSet.add(HashSet.java:219)
at com.michelin.cio.hudson.plugins.rolestrategy.RoleMap$1.perform(RoleMap.java:310)
at com.michelin.cio.hudson.plugins.rolestrategy.RoleMap$RoleWalker.walk(RoleMap.java:387)
at com.michelin.cio.hudson.plugins.rolestrategy.RoleMap$RoleWalker.<init>(RoleMap.java:376)
at com.michelin.cio.hudson.plugins.rolestrategy.RoleMap$1.<init>(RoleMap.java:307)
at com.michelin.cio.hudson.plugins.rolestrategy.RoleMap.getRolesHavingPermission(RoleMap.java:307)
at …
=> [JENKINS-18377] Cache Role#hashCode to speed up RoleMap#getRolesHavingPermission

src/main/java/com/michelin/cio/hudson/plugins/rolestrategy/RoleBasedAuthorizationStrategy.java, src/main/java/com/michelin/cio/hudson/plugins/rolestrategy/RoleMap.java
I added the unassign to api with 
Example: curl -X POST localhost:8080/role-strategy/strategy/unassignRole --data "type=globalRoles&amp;roleName=AMD&amp;sid=username"
and I added the GET function api to return all roles and their groups with
Example: curl -X GET localhost:8080/role-strategy/strategy/getAllRoles
Result json: {roleName: ['group1', 'group2'], roleName : ''}
=> Add GET Roles and UnassignRole to REST API

pom.xml, src/main/java/com/michelin/cio/hudson/plugins/rolestrategy/RoleBasedAuthorizationStrategy.java
Just another proof that we need more integration testing :( The tests were working like a charm with Matrix Auth 1.0, but updating to 1.5+ reproduced the issue immediately.
@daniel-beck restricted the new incarnation of `GlobalMatrixAuthorizationStrategy.DescriptorImpl#showPermission(Permission)` method in Matrix Auth 2.0, so I decided to just stop calling the implementation there. Before 1.5 the method was just calling `p.enabled()` anyway: https://github.com/jenkinsci/matrix-auth-plugin/blob/matrix-auth-1.4/src/main/java/hudson/security/GlobalMatrixAuthorizationStrategy.java#L306
https://issues.jenkins-ci.org/browse/JENKINS-47265
@reviewbybees @daniel-beck
=> [JENKINS-47265] - Stop requiring Matrix Auth flags to show Dangerous permissions

pom.xml, src/main/java/com/michelin/cio/hudson/plugins/rolestrategy/Role.java, src/test/java/com/michelin/cio/hudson/plugins/rolestrategy/RoleTest.java
Add a null filter when creating a new `Role`. When creating a new `Role` through groovy init script one can add a null `Permission` by mistake (using a permission from an non-installed plugin). Mainly because `Permission.fromId("package.permission.name")`, often used to retrieved a permission, could easily return null by mistake. Yet this will no throw an exception until trying to save the jenkins instance. 
If you don't save the jenkins instance to xml, null permission are ignored, and you will not get any feedback. If you save the jenkins instance, you will get a NPE and `java.lang.RuntimeException` :
```stacktrace
java.lang.RuntimeException: Failed to serialize jenkins.model.Jenkins#authorizationStrategy for class hudson.model.Hudson
at …
```
=> Null permissions fix

src/main/java/com/michelin/cio/hudson/plugins/rolestrategy/Role.java, src/main/java/com/michelin/cio/hudson/plugins/rolestrategy/RoleBasedAuthorizationStrategy.java, src/main/java/com/michelin/cio/hudson/plugins/rolestrategy/RoleMap.java, src/main/java/org/jenkinsci/plugins/rolestrategy/permissions/DangerousPermissionAdministrativeMonitor.java, src/main/java/org/jenkinsci/plugins/rolestrategy/permissions/PermissionHelper.java, src/test/java/org/jenkinsci/plugins/rolestrategy/DangerousPermissionsTest.java
Upstream of https://github.com/jenkinsci/configuration-as-code-plugin/pull/68 . It also improves the System Groovy Script use-cases by offering standard API. https://github.com/oleg-nenashev/demo-jenkins-config-as-code/blob/master/init_scripts/src/main/groovy/io/jenkins/systemgroovy/plugins/OwnershipBasedSecurityHelper.groovy
=> Extend plugin API to improve support of configuration-as-code use-cases

src/main/java/com/michelin/cio/hudson/plugins/rolestrategy/RoleBasedAuthorizationStrategy.java
According to improve this method without change its previous behavior, a new Queryparameter was added to getAllRoles method in RoleBasedAuthorizationStrategy. It may be useful in some case.
Thanks!
=> Add optional Queryparameter to getAllRoles Service

src/main/java/com/michelin/cio/hudson/plugins/rolestrategy/RoleBasedAuthorizationStrategy.java
When adding the **first** _projectRole_ through the addRole service, if _overwrite_ is set to true a NullPointerException is raised. Ie:
```sh
curl JENKINS_URL/role-strategy/strategy/addRole --data "type=projectRoles&roleName=ADM&permissionIds=hudson.model.Item.Read&overwrite=true"
```
This PR addresses that by adding a null check before trying to replace the previous role.
=> Fix null pointer in addRole Service

src/main/java/com/michelin/cio/hudson/plugins/rolestrategy/RoleBasedAuthorizationStrategy.java
In the current version, because the writer is not closed, no response can be obtained during the actual call to the api.
=> close doGetAllRoles resp writer

src/main/java/com/michelin/cio/hudson/plugins/rolestrategy/RoleBasedAuthorizationStrategy.java
add api to get role's permission & pattern
=> add do get role api

src/main/resources/com/michelin/cio/hudson/plugins/rolestrategy/RoleStrategyConfig/manage-roles.jelly
It was being displayed Manage and Assign Roles in Manage Roles page as title.
=> Change it.displayName to it.manageRolesName in manage-roles.jelly file

src/main/java/com/michelin/cio/hudson/plugins/rolestrategy/RoleBasedAuthorizationStrategy.java, src/main/java/com/michelin/cio/hudson/plugins/rolestrategy/RoleMap.java
my attempt to fix the issue(55804,Performance: Reduce memory footprint and execution time for RoleMap#newMatchingRoleMap()	)by removing the intermediate collections in the method newMatchingRoleMap(), which were created on call of getMatchingRoles() fuction.
=> [JENKINS-55804] - Attempt to solve issue

src/main/java/com/michelin/cio/hudson/plugins/rolestrategy/RoleBasedAuthorizationStrategy.java, src/main/java/com/michelin/cio/hudson/plugins/rolestrategy/RoleMap.java
In my usage scenario, I will insert a lot of roles. The order of insertion is slow for me.When I try to add a role concurrently, I get an exception.  
So I tried to use a concurrent safe container to store the role.And I packaged the plugin and tested the concurrent inserts in my environment.No exceptions continue to appear, and everything seems to be normal.  
Although replacing the container does not solve all the concurrency problems, I think it is effective for concurrent insertion of non-duplicate data.
=> [JENKINS-54900] improve concurrent security

src/main/java/com/michelin/cio/hudson/plugins/rolestrategy/RoleMap.java
I propose a fairly simple approach of both the problems listed: A class variable abort which when set to true terminates the loop and making the collection roles as global variable of outer class solves the issue of it being created on every call of walk().https://issues.jenkins-ci.org/browse/JENKINS-55916
=> [JENKINS-55916] optimising rolewalker, introducing abort method.

Jenkinsfile, pom.xml, src/test/java/jmh/BenchmarkRunner.java
Run benchmarks separately from the main build
Follow-up to #63
=> [JENKINS-57425] Run benchmarks only when a special Maven profile is defined

src/test/java/jmh/BenchmarkRunner.java, src/test/java/jmh/benchmarks/RoleMapBenchmark.java
Adds a benchmark for `RoleMap#hasPermission`.
Benchmark Reports: [jmh-report.txt](https://github.com/jenkinsci/role-strategy-plugin/files/3227535/jmh-report.txt) (JSON file; GitHub doesn't allow .json extension)
Takes much longer with increased number of roles.
@jenkinsci/gsoc2019-role-strategy
=> Add a benchmark for RoleMap#hasPermission

src/test/java/jmh/benchmarks/MaliciousRegexBenchmark.java
This malicious regex takes a lot of time to evaluate. This is what I had used for the Docker configuration in #62 . Now each operation takes ~ 100 ms.
=> Add a benchmark using a Malicious Regex

src/test/java/jmh/JmhJenkinsRule.java, src/test/java/jmh/benchmarks/WebClientBenchmark.java
Adds support for running WebClient in JMH benchmarks.
Draft until jQuery from #50 is 404 from the following test:
```java
public class RandomTest {
@Rule
public JenkinsRule j = new JenkinsRule();
@Test
public void test() throws Exception {
JenkinsRule.WebClient webClient = j.createWebClient();
webClient.login("user34", "user34");
webClient.goTo("");
}
}
```
@jenkinsci/gsoc2019-role-strategy
=> Add support of WebClient-based tests for REST API and Web UI benchmarks

src/test/java/jmh/JmhJenkinsRule.java, src/test/java/jmh/benchmarks/MaliciousRegexBenchmark.java, src/test/java/jmh/benchmarks/WebClientBenchmark.java
Also remove cache from WebClient for measuring actual load times.
=> Update MaliciousRegexBenchmark to compare page render times and time to check READ permission

src/test/java/jmh/benchmarks/FolderAccessBenchmark.java
Benchmarks `newMatchingRoleMap` as all of the regex matching takes place there
Also use `Sets.newHashSet` instead of `new HashSet(Arrays.asList(...))`.
=> Add new benchmark for RoleMap#newMatchingRoleMap

src/main/java/com/michelin/cio/hudson/plugins/rolestrategy/RoleMap.java
From our discussion yesterday on the Gitter chat and since the newMatchingRoleMap is called for every ACL request and a lot of permissions are checked for a project when the home page loads, having a cache avoids checking regular expressions again for every time permission checks are called for a given Item.
=> Performance: Cache RoleMaps produced by `RoleMap#newMatchingRoleMap()`

src/main/java/com/michelin/cio/hudson/plugins/rolestrategy/RoleBasedAuthorizationStrategy.java
`grantedRoles` in `RoleBasedAuthorizationStrategy` used String keys for getting values from the map. This changes it to use `RoleType` enum keys.
=> Refactor RoleBasedAuthorizationStrategy to use Enum keys

src/main/java/com/michelin/cio/hudson/plugins/rolestrategy/RoleMap.java, src/main/java/org/jenkinsci/plugins/rolestrategy/permissions/DangerousPermissionHandlingMode.java, src/main/java/org/jenkinsci/plugins/rolestrategy/permissions/PermissionHelper.java, src/test/java/org/jenkinsci/plugins/rolestrategy/DangerousPermissionsTest.java
The permissions that a imply a permission are calculated every time. This pull request caches the results in a  `ConcurrentHashMap`.
=> [JENKINS-58399] Performance: Avoid finding implying permissions on each `hasPermission()` call

src/main/java/org/jenkinsci/plugins/rolestrategy/RoleBasedProjectNamingStrategy.java
Came across this minor optimization when looking through the codebase
=> Role-Based Project Naming Strategy: Do not iterate through roles for blank names

CONTRIBUTORS
Deletes the file, which may confuse some people. There is no specific contributing guidelines in the repository ATM
An alternative is to use https://github.com/all-contributors/all-contributors , but it would require some time to configure it for the repo
=> Delete the obsolete CONTRIBUTORS file

.dependabot/config.yml
https://groups.google.com/forum/#!topic/jenkinsci-dev/XMllKuWLO_8
Ignoring plugins and Jenkins core for now
=> Enable Dependabot to keep development tools up to date

src/main/java/com/michelin/cio/hudson/plugins/rolestrategy/RoleBasedAuthorizationStrategy.java, src/main/resources/com/michelin/cio/hudson/plugins/rolestrategy/Messages.properties, src/main/resources/com/michelin/cio/hudson/plugins/rolestrategy/RoleStrategyConfig/assign-global-roles.jelly, src/main/resources/com/michelin/cio/hudson/plugins/rolestrategy/RoleStrategyConfig/assign-project-roles.jelly, src/main/resources/com/michelin/cio/hudson/plugins/rolestrategy/RoleStrategyConfig/assign-slave-roles.jelly
When copy&pasting data in the user and group field of the Assign Roles page, it often happens that some trailing whitespace is included. This whitespace was left in the value and led to permission problems that were very difficult to debug, as the whitespace is only visible when reviewing the config.xml
This change trims the value and issues a warning when doing so.
I don't expect anybody to seriously use user or groups with leading or trailing whitespace. But if anybody does, he is warned about this change.
=> [JENKINS-56391] Trim whitespace from user/groups when assigning roles

src/main/java/com/synopsys/arc/jenkins/plugins/rolestrategy/RoleMacroExtension.java
Signed-off-by: Raihaan Shouhell <raihaan.shouhell@autodesk.com>
Adds a cache for parsed macros. From what I gather this does static one time parsing so the cache doesn't seem like it needs expiry
jmh seems to indicate this as an overall perf win:
=> Cache Role Macros to improve the permission check performance

src/main/java/com/michelin/cio/hudson/plugins/rolestrategy/RoleBasedAuthorizationStrategy.java, src/main/java/com/michelin/cio/hudson/plugins/rolestrategy/RoleMap.java, src/main/java/com/synopsys/arc/jenkins/plugins/rolestrategy/Macro.java, src/main/java/com/synopsys/arc/jenkins/plugins/rolestrategy/RoleType.java, src/main/java/org/jenkinsci/plugins/rolestrategy/RoleBasedProjectNamingStrategy.java, src/main/java/org/jenkinsci/plugins/rolestrategy/casc/RoleBasedAuthorizationStrategyConfigurator.java, src/main/java/org/jenkinsci/plugins/rolestrategy/permissions/DangerousPermissionHandlingMode.java, src/main/java/org/jenkinsci/plugins/rolestrategy/permissions/PermissionHelper.java, src/test/java/jmh/benchmarks/CascBenchmark.java, src/test/java/org/jenkinsci/plugins/rolestrategy/RoleStrategyTest.java, src/test/performance/init_scripts/src/main/groovy/io/jenkins/systemgroovy/plugins/PipelineHelper.groovy
Minor cleanups and update the since/todo comments
=> Fix `@since` fields in Javadoc + Use the new Role Strategy APIs with enum in the naming strategy and tests

pom.xml
JCasc had to create a new dependency that wasn't a `tests` classifier because maven doesn't allow you to bring dependencies through classifiers.
Upgrading here so that PCT works again,
Tracking:
https://github.com/jenkinsci/bom/pull/164
Note: We'll need a release for PCT please
=> Upgrade the JCasC dependency to 1.35

src/main/resources/com/michelin/cio/hudson/plugins/rolestrategy/RoleStrategyConfig/assign-global-roles.jelly, src/main/resources/com/michelin/cio/hudson/plugins/rolestrategy/RoleStrategyConfig/assign-project-roles.jelly, src/main/resources/com/michelin/cio/hudson/plugins/rolestrategy/RoleStrategyConfig/assign-roles.jelly, src/main/resources/com/michelin/cio/hudson/plugins/rolestrategy/RoleStrategyConfig/assign-slave-roles.jelly
Hello,
In addition to the replication of header row and first column, adding a tooltips (like some GreaseMonkey scripts are doing) is also very useful
This pull request will allow to add this tooltip if you think it can be interesting.
=> Add Tooltips on Assign Role table

src/main/java/com/michelin/cio/hudson/plugins/rolestrategy/RoleBasedAuthorizationStrategy.java
Compatibility with https://github.com/jenkinsci/jenkins/pull/4944.
=> Use ExtendedHierarchicalStreamReader to ensure compatibility with upstream XStream versions

src/main/java/com/michelin/cio/hudson/plugins/rolestrategy/RoleStrategyConfig.java
For Jenkins 2.226+, move the "Manage and Assign Roles" into the "Security" category.
Note that implementing this does not require bumping jenkins core dependency to a recent version, so the change proposed here is really minimal.
=> set configuration category

Jenkinsfile
Needed to stabilize the `master` branch and to make the builds green for #139 . It also disables benchmarks which are not very stable at the moment . CC @AbhyudayaSharma @timja
=> Update configurations in the CI pipeline, temporarily disable benchmarks

pom.xml, src/main/java/com/michelin/cio/hudson/plugins/rolestrategy/RoleStrategyConfig.java
the core version is new enough that this is no longer needed
cc @oleg-nenashev @res0nance
=> Remove strict dependency on Extended Read Permission plugin

src/main/java/com/michelin/cio/hudson/plugins/rolestrategy/RoleMap.java, src/test/java/com/michelin/cio/hudson/plugins/rolestrategy/APITest.java
The cache (implemented in #115) is not invalidated when there is an assignment or un-assignment of roles to users, causing the users permissions to not be updated. This change adds invalidation for assignment and unassignment. I've also added web API tests.
=> [JENKINS-61470, JENKINS-61508] Invalidate cache for assign and unassign

src/test/performance/init_scripts/src/main/groovy/scripts/Docker.groovy
As mentioned in https://www.jenkins.io/blog/2020/05/06/docker-agent-image-renaming/ and https://issues.jenkins-ci.org/browse/JENKINS-42846
=> Hacktoberfest - Rename jenkins/jnlp-slave -> jenkins/inbound-agent

src/main/java/com/michelin/cio/hudson/plugins/rolestrategy/RoleMap.java
Rewrite the getMatchingJobNames() implementation to use preauth filtering
=> Performance: Use preauth filtering for matching names

src/test/performance/init_scripts/src/main/groovy/demo/jenkins-buildPlugin.groovy
Spotbugs reporting is being enabled by default in https://github.com/jenkins-infra/pipeline-library/pull/121, update to parent pom 4.x to use spotbugs instead of findbugs.
=> Remove unneeded configuration in buildPlugin

pom.xml, src/main/java/com/michelin/cio/hudson/plugins/rolestrategy/RoleMap.java
Guava provided from core is a cache library that probably can't be updated ever, use an updated library.
I re-ran the benchmarks as well
=> Swap from guava cache to caffeine

pom.xml, src/main/java/com/michelin/cio/hudson/plugins/rolestrategy/RoleBasedAuthorizationStrategy.java, src/main/java/com/michelin/cio/hudson/plugins/rolestrategy/ValidationUtil.java, src/main/resources/com/michelin/cio/hudson/plugins/rolestrategy/RoleStrategyConfig/assign-global-roles.jelly, src/main/resources/com/michelin/cio/hudson/plugins/rolestrategy/RoleStrategyConfig/assign-project-roles.jelly, src/main/resources/com/michelin/cio/hudson/plugins/rolestrategy/RoleStrategyConfig/assign-slave-roles.jelly, src/main/resources/com/michelin/cio/hudson/plugins/rolestrategy/RoleStrategyConfig/manage-roles.jelly
The only thing used from matrix-auth was the validation of user names.
Since matrix auth added a separation between users and groups the UI was
broken when matrix-auth 3.0 or newer was installed.
https://issues.jenkins.io/browse/JENKINS-68241
https://issues.jenkins.io/browse/JENKINS-67370
https://issues.jenkins.io/browse/JENKINS-67387
https://issues.jenkins.io/browse/JENKINS-67760
https://issues.jenkins.io/browse/JENKINS-67422
https://issues.jenkins.io/browse/JENKINS-67393
requires core 2.303.1 to make the icon stuff working
=> Remove dependency to matrix-auth plugin

src/main/java/com/michelin/cio/hudson/plugins/rolestrategy/RoleBasedAuthorizationStrategy.java, src/main/resources/com/michelin/cio/hudson/plugins/rolestrategy/RoleStrategyConfig/assign-global-roles.jelly, src/main/resources/com/michelin/cio/hudson/plugins/rolestrategy/RoleStrategyConfig/assign-project-roles.jelly, src/main/resources/com/michelin/cio/hudson/plugins/rolestrategy/RoleStrategyConfig/assign-roles.jelly, src/main/resources/com/michelin/cio/hudson/plugins/rolestrategy/RoleStrategyConfig/assign-slave-roles.jelly, src/main/resources/com/michelin/cio/hudson/plugins/rolestrategy/RoleStrategyConfig/manage-global-roles.jelly, src/main/resources/com/michelin/cio/hudson/plugins/rolestrategy/RoleStrategyConfig/manage-project-roles.jelly, src/main/resources/com/michelin/cio/hudson/plugins/rolestrategy/RoleStrategyConfig/manage-roles.jelly, src/main/resources/com/michelin/cio/hudson/plugins/rolestrategy/RoleStrategyConfig/manage-slave-roles.jelly, src/main/webapp/css/role-strategy.css
- display the permissions top down on the manage roles page
- display the roles top down on the assign roles page
do not show permission group header when the group doesn't contain any enabled permissions. E.g. by default Envinject permission is disabled, yet the header is shown but without any permission inside which leads to bad UI appearance.
Use bottombuttonbar so the save/apply buttons are always visible when one has many roles/users
=> UI enhancements

src/main/java/com/michelin/cio/hudson/plugins/rolestrategy/RoleBasedAuthorizationStrategy.java
[JENKINS-63413](https://issues.jenkins.io/browse/JENKINS-63413)
When using the Authorize Project plugin and trying to run as user that
started the build this wasn't working when the permission was only
granted on a node role and not on a global role.
Implementing the getACL(Node) method in favor of the getACL(Computer) solves the problem.
Other tickets
[JENKINS-60508](https://issues.jenkins.io/browse/JENKINS-60508)
[JENKINS-56834](https://issues.jenkins.io/browse/JENKINS-56834)
=> [JENKINS-63413] fix running as user on node

pom.xml, src/main/java/com/michelin/cio/hudson/plugins/rolestrategy/RoleBasedAuthorizationStrategy.java, src/test/java/org/jenkinsci/plugins/rolestrategy/AuthorizeProjectTest.java, src/test/java/org/jenkinsci/plugins/rolestrategy/ConfigurationAsCodeTest.java, src/test/java/org/jenkinsci/plugins/rolestrategy/OwnershipTest.java, src/test/java/org/jenkinsci/plugins/rolestrategy/RoleAssignmentTest.java, src/test/resources/org/jenkinsci/plugins/rolestrategy/AuthorizeProjectTest/config.xml, src/test/resources/org/jenkinsci/plugins/rolestrategy/OwnershipTest.yml
[JENKINS-68841](https://issues.jenkins.io/browse/JENKINS-68841)
Agent permissions except 'Build' work with a Computer object.
The change fixing [JENKINS-63413] caused a regression in combination
with the ownership plugin causing Agent permission to not work when
using the Ownermacros.
Added integrations tests with authorize-project and ownership plugins to
catch issues.
=> [JENKINS-68841] fix node ownership permission problem

src/main/resources/com/michelin/cio/hudson/plugins/rolestrategy/RoleStrategyConfig/assign-global-roles.jelly, src/main/resources/com/michelin/cio/hudson/plugins/rolestrategy/RoleStrategyConfig/assign-project-roles.jelly, src/main/resources/com/michelin/cio/hudson/plugins/rolestrategy/RoleStrategyConfig/assign-slave-roles.jelly
[JENKINS-68889](https://issues.jenkins.io/browse/JENKINS-68889)
After adding a new sid to a global or item on the assign roles page and
then hovering over the newly added line the highlighting was broken.
Instead of the column where hte mouse a column of the nodes roles was
highlighted.
=> [JENKINS-68889] fix highlighting on assign roles page

src/main/resources/com/michelin/cio/hudson/plugins/rolestrategy/RoleStrategyConfig/assign-global-roles.jelly, src/main/resources/com/michelin/cio/hudson/plugins/rolestrategy/RoleStrategyConfig/assign-project-roles.jelly, src/main/resources/com/michelin/cio/hudson/plugins/rolestrategy/RoleStrategyConfig/assign-slave-roles.jelly, src/main/resources/com/michelin/cio/hudson/plugins/rolestrategy/RoleStrategyConfig/manage-global-roles.jelly, src/main/resources/com/michelin/cio/hudson/plugins/rolestrategy/RoleStrategyConfig/manage-project-roles.jelly, src/main/resources/com/michelin/cio/hudson/plugins/rolestrategy/RoleStrategyConfig/manage-roles.jelly, src/main/resources/com/michelin/cio/hudson/plugins/rolestrategy/RoleStrategyConfig/manage-slave-roles.jelly
[JENKINS-68892](https://issues.jenkins.io/browse/JENKINS-68892)
Similar to the assign roles pages when hovering over the checkbox to
set the permissions for a role a tooltip is displayed showing the
permissions, the role and the pattern
=> [JENKINS-68892] add tooltips to manage roles page

src/main/resources/com/michelin/cio/hudson/plugins/rolestrategy/RoleStrategyConfig/assign-agent-roles.jelly, src/main/resources/com/michelin/cio/hudson/plugins/rolestrategy/RoleStrategyConfig/assign-global-roles.jelly, src/main/resources/com/michelin/cio/hudson/plugins/rolestrategy/RoleStrategyConfig/assign-project-roles.jelly, src/main/resources/com/michelin/cio/hudson/plugins/rolestrategy/RoleStrategyConfig/assign-roles.jelly, src/main/resources/com/michelin/cio/hudson/plugins/rolestrategy/RoleStrategyConfig/manage-agent-roles.jelly, src/main/resources/com/michelin/cio/hudson/plugins/rolestrategy/RoleStrategyConfig/manage-global-roles.jelly, src/main/resources/com/michelin/cio/hudson/plugins/rolestrategy/RoleStrategyConfig/manage-project-roles.jelly, src/main/resources/com/michelin/cio/hudson/plugins/rolestrategy/RoleStrategyConfig/manage-roles.jelly, src/main/webapp/js/table.js
after adding a new role/user the tooltips when hovering over the
checkboxes where not properly escaped which is a potential XSS.
But it applies only to admin so no real security risk.
Also fixes JENKINS-55414 where patterns were double escaped without
need.
=> [JENKINS-68870] properly escape tooltip texts

src/main/java/com/michelin/cio/hudson/plugins/rolestrategy/RoleBasedAuthorizationStrategy.java, src/main/java/com/michelin/cio/hudson/plugins/rolestrategy/RoleMap.java, src/main/resources/com/michelin/cio/hudson/plugins/rolestrategy/RoleStrategyConfig/manage-agent-roles.jelly, src/main/resources/com/michelin/cio/hudson/plugins/rolestrategy/RoleStrategyConfig/manage-project-roles.jelly, src/main/resources/com/michelin/cio/hudson/plugins/rolestrategy/RoleStrategyConfig/manage-roles.jelly
It is now possible to click on the regex for agents. 
This will show a popup with the the first 10 agents matching the given pattern similar to when clicking n the regex for items
=> [JENKINS-63528] add possibility to check for regex of agent roles

src/main/resources/com/michelin/cio/hudson/plugins/rolestrategy/RoleStrategyConfig/assign-global-roles.jelly, src/main/resources/com/michelin/cio/hudson/plugins/rolestrategy/RoleStrategyConfig/assign-project-roles.jelly, src/main/resources/com/michelin/cio/hudson/plugins/rolestrategy/RoleStrategyConfig/assign-roles.jelly, src/main/resources/com/michelin/cio/hudson/plugins/rolestrategy/RoleStrategyConfig/index.jelly, src/main/resources/com/michelin/cio/hudson/plugins/rolestrategy/RoleStrategyConfig/manage-global-roles.jelly, src/main/resources/com/michelin/cio/hudson/plugins/rolestrategy/RoleStrategyConfig/manage-project-roles.jelly, src/main/resources/com/michelin/cio/hudson/plugins/rolestrategy/RoleStrategyConfig/manage-roles.jelly, src/main/webapp/js/assignFilters.js, src/main/webapp/js/manageFilters.js
With the new filters managing of roles and user will become easier.
On the manage roles pages when adding more than 10 roles, the filter is
shown and when getting below 10 it is hidden.
On the assign roles page the input to filter roles will be enabled when
more than 20 roles are configured.
The input to filter users/groups will be enabled when more than 10 users
are added. The input is dynamic and will automatically appear when
adding the 11th user/group.
The filters are case insensitive
=> [JENKINS-56525] Add filters for roles and users

README.md, src/main/resources/com/michelin/cio/hudson/plugins/rolestrategy/RoleStrategyConfig/assign-agent-roles.jelly, src/main/resources/com/michelin/cio/hudson/plugins/rolestrategy/RoleStrategyConfig/assign-global-roles.jelly, src/main/resources/com/michelin/cio/hudson/plugins/rolestrategy/RoleStrategyConfig/assign-project-roles.jelly, src/main/resources/com/michelin/cio/hudson/plugins/rolestrategy/RoleStrategyConfig/assign-roles.jelly, src/main/resources/com/michelin/cio/hudson/plugins/rolestrategy/RoleStrategyConfig/manage-roles.jelly
Add a tooltip to the right delete symbol showing the role or user
On assign roles:
- add a tooltip to the header row with the permissions and for items and
nodes also the pattern
- add the pattern to the tooltip of the checkboxes for items and nodes
=> improve tooltips

src/main/java/com/michelin/cio/hudson/plugins/rolestrategy/RoleBasedAuthorizationStrategy.java, src/main/java/com/michelin/cio/hudson/plugins/rolestrategy/RoleMap.java, src/main/resources/com/michelin/cio/hudson/plugins/rolestrategy/RoleStrategyConfig/manage-agent-roles.jelly, src/main/resources/com/michelin/cio/hudson/plugins/rolestrategy/RoleStrategyConfig/manage-global-roles.jelly, src/main/resources/com/michelin/cio/hudson/plugins/rolestrategy/RoleStrategyConfig/manage-project-roles.jelly
[JENKINS-68935](https://issues.jenkins.io/browse/JENKINS-68935)
When clicking on a pattern, the popup now gives a hint how many items match the pattern when more than 10 items match.
The number of matched items shown is still limited to 10.
=> [JENKINS-68935] Show hint when pattern matches more than 10 items

src/main/webapp/css/role-strategy.css, src/main/webapp/js/table.js
On Jenkins 2.335+ the table highlighter didn't work anymore due to
changed layouting for inputs.
Also when using a dark theme, the text was unreadable when highlighted.
=> fix tablehighlighter for newer Jenkins versions

src/main/java/com/michelin/cio/hudson/plugins/rolestrategy/RoleBasedAuthorizationStrategy.java
it is sufficient to just grant Jenkins.ADMINISTER permission when
creating the admin role after enabling the plugin.
All other permissions are implied by it so there is no need to
explicitly grant them.
=> admin role with only Jenkins.ADMINISTER

src/main/webapp/js/table.js
fixing the tablehighlighter for newer Jenkins version introduced a
regression when highlighting the permissions for items and agents
=> fix regression in table highlighter

src/main/java/org/jenkinsci/plugins/rolestrategy/RoleBasedProjectNamingStrategy.java, src/test/java/org/jenkinsci/plugins/rolestrategy/RoleBasedProjectNamingStrategyTest.java
A DSL seed job will try to create jobs as the SYSTEM user unless the authorize project plugin is used.
Anyway SYSTEM user should have no restrictions.
=> [JENKINS-69625] SYSTEM user should be able to create any job

pom.xml
This PR updates the `developerConnection` to use the standard format used in other Jenkins plugins and the archetype. This format is less likely to cause problems for Plugin Compatibility Tester (PCT) and Maven Release Plugin (MRP).
=> Use standard `developerConnection` format

Jenkinsfile
The plugin's baseline contains everything we need.
=> Unpin jenkins version for JDK 17 tests

README.md
The current script missed to add permissions at all. To grant admin permission it is sufficient to just add the JENKINS.ADMINISTER permission.
=> [JENKINS-69690] fix example script in README

src/main/resources/org/jenkinsci/plugins/rolestrategy/NamingStrategyAdministrativeMonitor/message.jelly
Reverts jenkinsci/role-strategy-plugin#248 because we're reverting the core PR.
=> Revert "Forward compatibility with jenkins-buttons"

Jenkinsfile, pom.xml
Updates the required Jenkins version to the [currently recommended one](https://www.jenkins.io/doc/developer/plugin-development/choosing-jenkins-baseline/).
Since support for Java 8 has been dropped it's necessary to update the Jenkinsfile (configuration taken from [archetype Jenkinsfile](https://github.com/jenkinsci/archetypes/blob/a3f4d5886f27add50e44672d7c7c0f89d3c319d6/common-files/Jenkinsfile).
:warning: Doing changes to the Jenkinsfile need someone with write permission @mawinter69 
----------------------
=> Update to Jenkins 2.361.4 LTS

src/main/java/com/michelin/cio/hudson/plugins/rolestrategy/RoleMap.java, src/test/java/com/michelin/cio/hudson/plugins/rolestrategy/GrantingDisabledPermissionTest.java
Integrate fix for SECURITY-3053 into `master` branch.
We cannot easily integrate the branch from which 587.588.v850a_20a_30162 was released, since it changes the `pom.xml`. Rather than undo that separately, it's probably easiest to use this cherry-pick of the security fix at https://github.com/jenkinsci/role-strategy-plugin/commit/850a20a3016276d0c0ba4898a876c113a9191da4 that removes the changes to `pom.xml` and treat the branch like a back-port branch.
**IMPORTANT:** I've made the `master` branch read-only to prevent accidental releases from merging other PRs that do not contain this security fix. Uncheck "Lock branch" and "Do not allow bypassing the above settings" to restore the previous configuration.
=> [SECURITY-3053]

src/main/resources/com/michelin/cio/hudson/plugins/rolestrategy/RoleStrategyConfig/assign-roles.jelly, src/main/resources/com/michelin/cio/hudson/plugins/rolestrategy/RoleStrategyConfig/manage-roles.jelly, src/main/webapp/js/tableAssign.js, src/main/webapp/js/tableManage.js
Jenkins 2.379 changed the tooltips from YUI to tippy. As the tooltips contain html, the html was escaped and not printed properly. Also fixes an issue with the pattern edit that stopped working after using the svg icon from ionicons for just added roles
=> [JENKINS-71074] fix tooltips

docs/DEVELOPER.md, src/main/webapp/js/tableManage.js
The fix for the tooltips introduced a regression in adding global roles. As there is no pattern for global roles the query to find the pencil icon returns nothing making the javascript fail.
=> [JENKINS-71098] fix adding global roles

src/main/resources/com/michelin/cio/hudson/plugins/rolestrategy/RoleStrategyConfig/assign-roles.jelly, src/main/resources/com/michelin/cio/hudson/plugins/rolestrategy/RoleStrategyConfig/index.jelly, src/main/webapp/js/tableAssign.js, src/main/webapp/js/tableManage.js
Warn when leaving the manage/assign roles pages and there are changes which are not saved.
Detects also deletions of entries.
[JENKINS-71145](https://issues.jenkins.io/browse/JENKINS-71145)
=> [JENKINS-71145] warn when leaving with unsaved changes

src/main/resources/com/michelin/cio/hudson/plugins/rolestrategy/RoleStrategyConfig/assign-agent-roles.jelly, src/main/resources/com/michelin/cio/hudson/plugins/rolestrategy/RoleStrategyConfig/assign-global-roles.jelly, src/main/resources/com/michelin/cio/hudson/plugins/rolestrategy/RoleStrategyConfig/assign-project-roles.jelly, src/main/resources/com/michelin/cio/hudson/plugins/rolestrategy/RoleStrategyConfig/manage-agent-roles.jelly, src/main/resources/com/michelin/cio/hudson/plugins/rolestrategy/RoleStrategyConfig/manage-global-roles.jelly, src/main/resources/com/michelin/cio/hudson/plugins/rolestrategy/RoleStrategyConfig/manage-project-roles.jelly, src/main/resources/com/michelin/cio/hudson/plugins/rolestrategy/RoleStrategyConfig/sidepanel.jelly, src/main/webapp/js/table.js, src/main/webapp/js/tableAssign.js, src/main/webapp/js/tableManage.js
Some minor enhancements
- fixed a typo
- table highlighting works on the cell and not the input to avoid flickering when moving around the mouse
- highlight row when on the delete button on the right
Internal changes
- use template element instead of a hidden row that gets removed
- use `let` instead of `var`in js files where applicable
```[tasklist]
```
=> Minor enhancements

src/main/java/com/michelin/cio/hudson/plugins/rolestrategy/PermissionTemplate.java, src/main/java/com/michelin/cio/hudson/plugins/rolestrategy/Role.java, src/main/java/com/michelin/cio/hudson/plugins/rolestrategy/RoleBasedAuthorizationStrategy.java, src/test/java/com/michelin/cio/hudson/plugins/rolestrategy/ApiTest.java, src/test/java/jmh/benchmarks/MaliciousRegexBenchmark.java
It is now possible to add/update and removing templates via the REST API
When adding/updating a role you can now specify the template to use.
```[tasklist]
```
=> add REST API for templates

src/main/resources/com/michelin/cio/hudson/plugins/rolestrategy/RoleStrategyConfig/manage-project-roles.jelly, src/main/webapp/js/tableManage.js
when no template is selected the templatename field should be empty as well in the newly added line
```[tasklist]
```
=> fix adding role without template

pom.xml
JENKINS-71772 notes that https://github.com/jenkinsci/role-strategy-plugin/commit/a5f27678f6d61a330597b9b157ca7468158835f5 inadvertently changed the authorize-project plugin from a test dependency to a runtime dependency.  The code compiles correctly without the runtime dependency and the tests pass on my Linux computer with Java 11.
https://github.com/jenkinsci/bom/pull/2340 added authorize-project plugin to the plugin bill of materials because I didn't detect that the new dependency was not needed at runtime.
Thanks to James Holderness for reporting the issue.
Confirmed that compilation succeeds and automated tests pass with the authorize-project plugin dependency switched back to a test dependency instead of a runtime dependency.
=> [JENKINS-71772] Remove runtime dependency on authorize-project plugin

pom.xml
The most recent plugin bill of materials provides the authorize-project plugin version.  Use that version rather than managing the version drectly in the plugin pom.
Apache commons-lang3-api is available as an API plugin that is managed by the bom.  Test with the API plugin rather than including commons-lang3-api in the tests.  Testing with the API plugin has the added benefit that it is using the same version that is installed in many Jenkins controllers.
Automated tests pass on my Linux with Java 11.
=> Use plugin bom for dependency version definitions

src/main/resources/com/michelin/cio/hudson/plugins/rolestrategy/RoleStrategyConfig/index.jelly
when the table footer for item roles is shown (requires 20 or more roles) the template column didn't set a rowspan which made the permission group being offset by one.
[JENKINS-72879](https://issues.jenkins.io/browse/JENKINS-72870)
```[tasklist]
```
=> [JENKINS-72870] fix table footer for item roles

src/main/java/com/michelin/cio/hudson/plugins/rolestrategy/ValidationUtil.java
`loadGroupByGroupname2` returns a GroupDetails object. This has a getDisplayName method that we can use to show the actual groupname instead of the object_id for EntraID (AzureAD). 
```[tasklist]
```
=> [JENKINS-72984] read GroupDetails displayname and show in assign page

pom.xml, src/main/java/com/michelin/cio/hudson/plugins/rolestrategy/RoleBasedAuthorizationStrategy.java, src/main/java/com/michelin/cio/hudson/plugins/rolestrategy/RoleStrategyConfig.java, src/main/java/org/jenkinsci/plugins/rolestrategy/RoleBasedProjectNamingStrategy.java
=> Migration to Jakarta EE

pom.xml, src/test/java/com/michelin/cio/hudson/plugins/rolestrategy/ApiTest.java, src/test/java/com/michelin/cio/hudson/plugins/rolestrategy/GrantingDisabledPermissionTest.java, src/test/java/com/michelin/cio/hudson/plugins/rolestrategy/RoleTest.java, src/test/java/com/synopsys/arc/jenkins/plugins/rolestrategy/ContainedInViewTest.java, src/test/java/com/synopsys/arc/jenkins/plugins/rolestrategy/MacroTest.java, src/test/java/jmh/BenchmarkRunner.java, src/test/java/org/jenkinsci/plugins/rolestrategy/AuthorizeProjectTest.java, src/test/java/org/jenkinsci/plugins/rolestrategy/ConfigurationAsCodeTest.java, src/test/java/org/jenkinsci/plugins/rolestrategy/OwnershipTest.java, src/test/java/org/jenkinsci/plugins/rolestrategy/PermissionTemplatesTest.java, src/test/java/org/jenkinsci/plugins/rolestrategy/RoleBasedProjectNamingStrategyTest.java, src/test/java/org/jenkinsci/plugins/rolestrategy/RoleStrategyTest.java, src/test/java/org/jenkinsci/plugins/rolestrategy/Security2182Test.java, src/test/java/org/jenkinsci/plugins/rolestrategy/Security2374Test.java, src/test/java/org/jenkinsci/plugins/rolestrategy/UserAuthoritiesAsRolesTest.java, src/test/java/org/jenkinsci/plugins/rolestrategy/UserGroupSeparationTest.java, src/test/java/org/jenkinsci/plugins/rolestrategy/pipeline/UserGlobalRolesTest.java, src/test/java/org/jenkinsci/plugins/rolestrategy/pipeline/UserItemRolesTest.java
This PR aims to migrate all tests to JUnit5. Changes include:
* Migrate annotations and imports
* Migrate assertions
* Remove public visibility for test classes and methods
* Minor clean up
~~Some tests fail due to https://github.com/jenkinsci/jenkins-test-harness/issues/901 which will likely be fixed in plugin-pom 5.7. I'll update the PR once it is available.~~
Some tests fail due to https://github.com/jenkinsci/configuration-as-code-plugin/pull/2637 which will likely be fixed in an upcoming release of `configuration-as-code-plugin` via bom. I'll update the PR once it is available.
I am well aware that this is a quite large changeset however I hope that there is still interest in this PR and it will be reviewed.
If there are any questions, please do not hesitate to ping me.
=> Migrate tests to JUnit5

README.md, src/main/resources/com/michelin/cio/hudson/plugins/rolestrategy/RoleStrategyConfig/assign-agent-roles.jelly, src/main/resources/com/michelin/cio/hudson/plugins/rolestrategy/RoleStrategyConfig/assign-project-roles.jelly, src/main/resources/com/michelin/cio/hudson/plugins/rolestrategy/RoleStrategyConfig/assign-roles.jelly, src/main/webapp/js/tableAssign.js
The memory consumption goes up to over 7 GiB when there are 400 item roles and a one user/group for each role. In such a scenario the UI will need to show 160000 checkboxes.
A considerable part of the memory consumption could be attributed to the tooltips.
With such a large table also the highlighting becomes very laggy.
To improve the situation tooltips and table highlighting will be disabled when the number of checkboxes exceeds 40000 in the item roles table.
Add documentation how to overcome max form items and max form size in Jetty.
=> [JENKINS-75686] reduce browser memory consumption with many roles/users

src/main/java/com/michelin/cio/hudson/plugins/rolestrategy/RoleBasedAuthorizationStrategy.java
the getRoleAssignements wasn't properly declaring that it returns json. While with standard ASCII characters that didn't cause any problems the result was not properly interpreted on javascript side with Unicode characters.
With the given config from JENKINS-75726, the role assignments are properly shown now.
=> [JENKINS-75726] Set proper content type and encoding
