- pom.xml
- src/main/java/com/michelin/cio/hudson/plugins/rolestrategy/Role.java
- src/main/java/com/michelin/cio/hudson/plugins/rolestrategy/RoleMap.java
- src/main/java/com/michelin/cio/hudson/plugins/rolestrategy/RoleStrategyConfig.java
- src/main/java/com/synopsys/arc/jenkins/plugins/rolestrategy/IMacroExtension.java
- src/main/java/com/synopsys/arc/jenkins/plugins/rolestrategy/Macro.java
- src/main/java/com/synopsys/arc/jenkins/plugins/rolestrategy/MacroException.java
- src/main/java/com/synopsys/arc/jenkins/plugins/rolestrategy/MacroExceptionCode.java
- src/main/java/com/synopsys/arc/jenkins/plugins/rolestrategy/RoleMacroExtension.java
- src/main/java/com/synopsys/arc/jenkins/plugins/rolestrategy/RoleStrategyConfigExtension.java
- src/main/java/com/synopsys/arc/jenkins/plugins/rolestrategy/RoleType.java
- src/main/java/com/synopsys/arc/jenkins/plugins/rolestrategy/UserMacroExtension.java
- src/main/java/com/synopsys/arc/jenkins/plugins/rolestrategy/macros/BuildableJobMacro.java
- src/main/java/com/synopsys/arc/jenkins/plugins/rolestrategy/macros/LoggedUserMacro.java
- src/main/java/com/synopsys/arc/jenkins/plugins/rolestrategy/macros/StubMacro.java
- src/main/resources/com/michelin/cio/hudson/plugins/rolestrategy/RoleStrategyConfig/assign-global-roles.jelly
- src/main/resources/com/michelin/cio/hudson/plugins/rolestrategy/RoleStrategyConfig/assign-project-roles.jelly
- src/main/resources/com/michelin/cio/hudson/plugins/rolestrategy/RoleStrategyConfig/assign-roles.jelly
- src/main/resources/com/michelin/cio/hudson/plugins/rolestrategy/RoleStrategyConfig/assign-slave-roles.jelly
- src/main/resources/com/michelin/cio/hudson/plugins/rolestrategy/RoleStrategyConfig/index.jelly
- src/main/resources/com/michelin/cio/hudson/plugins/rolestrategy/RoleStrategyConfig/list-macros.jelly
- src/main/resources/com/michelin/cio/hudson/plugins/rolestrategy/RoleStrategyConfig/manage-global-roles.jelly
- src/main/resources/com/michelin/cio/hudson/plugins/rolestrategy/RoleStrategyConfig/manage-project-roles.jelly
- src/main/resources/com/michelin/cio/hudson/plugins/rolestrategy/RoleStrategyConfig/manage-roles.jelly
- src/main/resources/com/michelin/cio/hudson/plugins/rolestrategy/RoleStrategyConfig/manage-slave-roles.jelly
- src/main/resources/index.jelly
- src/test/java/com/synopsys/arc/jenkins/plugins/rolestrategy/MacroTest.java
> Migrate to the new parent POM

- src/main/webapp/help/help-pattern.html
https://issues.jenkins-ci.org/browse/JENKINS-35250
> [FIXED JENKINS-35250] - Generalize the help message for patterns

- src/main/java/com/michelin/cio/hudson/plugins/rolestrategy/RoleMap.java
- src/main/java/org/jenkinsci/plugins/rolestrategy/Settings.java
- src/test/java/org/jenkinsci/plugins/rolestrategy/UserAuthoritiesAsRolesTest.java
This change should solve the reported performance issues.
https://issues.jenkins-ci.org/browse/JENKINS-35515
@reviewbybees @jenkinsci/code-reviewers @bkmeneguello
> [JENKINS-35515] - Fix the performance issue (regression in 2.3.0)

- src/main/resources/com/michelin/cio/hudson/plugins/rolestrategy/RoleStrategyConfig/list-macros.jelly
CC @jenkinsci/code-reviewers 
https://issues.jenkins-ci.org/browse/JENKINS-38230
> [FIXED JENKINS-38230] - Fixed escaping of descriptions in the Role Strategy Macros list

- src/main/java/com/michelin/cio/hudson/plugins/rolestrategy/RoleBasedAuthorizationStrategy.java
- src/main/java/com/michelin/cio/hudson/plugins/rolestrategy/RoleMap.java
- src/main/java/com/michelin/cio/hudson/plugins/rolestrategy/RoleStrategyConfig.java
Another go on PR #12 which seems abandoned
> Picking up "Added API to add roles and SIDs #12"

- src/main/java/com/michelin/cio/hudson/plugins/rolestrategy/RoleBasedAuthorizationStrategy.java
- src/main/java/com/michelin/cio/hudson/plugins/rolestrategy/RoleMap.java
- src/main/java/com/michelin/cio/hudson/plugins/rolestrategy/RoleStrategyConfig.java
In our environment it is very helpful to add roles and SIDs per API, therefore we added such a possibility. It could be very helpful for other users.
> Added API to add roles and SIDs

- src/main/java/com/michelin/cio/hudson/plugins/rolestrategy/RoleBasedAuthorizationStrategy.java
Actually I want to do the full refactoring of the Role management logic + add REST API docs, but I have no capacity to do it right now
> Polish REST API command Javadoc towards 2.5.0

- pom.xml
- src/main/java/com/michelin/cio/hudson/plugins/rolestrategy/RoleBasedAuthorizationStrategy.java
- src/main/java/com/michelin/cio/hudson/plugins/rolestrategy/RoleMap.java
- src/main/java/com/michelin/cio/hudson/plugins/rolestrategy/RoleStrategyConfig.java
- src/main/java/com/synopsys/arc/jenkins/plugins/rolestrategy/RoleMacroExtension.java
- src/main/java/com/synopsys/arc/jenkins/plugins/rolestrategy/UserMacroExtension.java
- src/main/java/org/jenkinsci/plugins/rolestrategy/RoleBasedProjectNamingStrategy.java
- src/main/java/org/jenkinsci/plugins/rolestrategy/permissions/DangerousPermissionHelper.java
- src/test/java/org/jenkinsci/plugins/rolestrategy/RoleAssignmentTest.java
@reviewbybees @jenkinsci/code-reviewers just in case somebody is interested
> Plugin facelift towards the 2.6.0 Release

- src/main/java/com/michelin/cio/hudson/plugins/rolestrategy/RoleBasedAuthorizationStrategy.java
NPE occurs when the parameter I transfer is a non-existing role type
> add doGetAllRoles NPE check

- pom.xml
- src/main/java/com/michelin/cio/hudson/plugins/rolestrategy/RoleBasedAuthorizationStrategy.java
- src/main/java/org/jenkinsci/plugins/rolestrategy/RoleBasedProjectNamingStrategy.java
- src/main/java/org/jenkinsci/plugins/rolestrategy/permissions/DangerousPermissionAdministrativeMonitor.java
- src/main/resources/com/michelin/cio/hudson/plugins/rolestrategy/Messages.properties
- src/test/java/org/jenkinsci/plugins/rolestrategy/UserAuthoritiesAsRolesTest.java
Cleans up some historic stuff which is no longer required.
I do not want to keep support of old versions anymore, 2.60.3 is almost 2 years old
> Require Jenkins core 2.60.3 in Role Strategy.

- README.md
Just a quick patch for the README page
> Add Gitter link to the README + Cleanup old docs

- src/main/java/com/michelin/cio/hudson/plugins/rolestrategy/RoleMap.java
Fix for https://issues.jenkins-ci.org/browse/JENKINS-57432
> [JENKINS-57432] Pattern preview doesn't work with folders

- LICENSE.md
- README.md
Just a first baby step w.r.t moving documentation from Wiki to GitHub.
> Cleanup the readme page

- src/test/java/jmh/benchmarks/CascBenchmark.java
Benchmarks the creation of ACL objects. Follow-up on the benchmarks introduced in #63
> Add a benchmark for creation of ACL objects

- pom.xml
- src/test/java/jmh/BenchmarkFinder.java
- src/test/java/jmh/BenchmarkRunner.java
- src/test/java/jmh/JmhBenchmark.java
- src/test/java/jmh/benchmarks/CascBenchmark.java
- src/test/java/jmh/benchmarks/PermissionBenchmark.java
- src/test/java/jmh/benchmarks/RoleMapBenchmark.java
As suggested by @oleg-nenashev in #67 , this pull request allows the framework to automatically detect benchmark classes.
> [JENKINS-57730] Automatically detect JMH benchmark classes

- src/test/java/jmh/benchmarks/PermissionBenchmark.java
- src/test/java/jmh/benchmarks/RoleMapBenchmark.java
Adds benchmarks for multiple roles as requested by @runzexia .
> Add hasPermission benchmarks for 100, 200 and 500 roles

- src/test/java/jmh/benchmarks/CascBenchmark.java
- src/test/java/jmh/benchmarks/FolderAccessBenchmark.java
Create a benchmark accessing a `FreeStyleProject` in a 2-level nested folder.
@jenkinsci/gsoc2019-role-strategy @Straber
> Add Folder benchmark based on Straber's configuration

- README.md
> Add Release reference badges to the README

- README.md
- docs/DEVELOPER.md
Just adding a stub for developer documentation which can be improved later
> Create a developer documentation page

- src/main/java/com/michelin/cio/hudson/plugins/rolestrategy/Role.java
- src/main/java/com/michelin/cio/hudson/plugins/rolestrategy/RoleBasedAuthorizationStrategy.java
- src/main/java/com/michelin/cio/hudson/plugins/rolestrategy/RoleMap.java
- src/main/java/com/michelin/cio/hudson/plugins/rolestrategy/RoleStrategyConfig.java
- src/main/java/com/synopsys/arc/jenkins/plugins/rolestrategy/IMacroExtension.java
- src/main/java/com/synopsys/arc/jenkins/plugins/rolestrategy/Macro.java
- src/main/java/com/synopsys/arc/jenkins/plugins/rolestrategy/MacroException.java
- src/main/java/com/synopsys/arc/jenkins/plugins/rolestrategy/RoleType.java
- src/main/java/com/synopsys/arc/jenkins/plugins/rolestrategy/UserMacroExtension.java
- src/main/java/org/jenkinsci/plugins/rolestrategy/Settings.java
- src/main/java/org/jenkinsci/plugins/rolestrategy/permissions/DangerousPermissionAdministrativeMonitor.java
- src/main/java/org/jenkinsci/plugins/rolestrategy/permissions/DangerousPermissionHandlingMode.java
- src/main/java/org/jenkinsci/plugins/rolestrategy/permissions/PermissionHelper.java
Just a cosmetic change, not altering plugin behaviour.
> Cleanup whitespaces in the code

- pom.xml
- src/main/java/com/michelin/cio/hudson/plugins/rolestrategy/RoleBasedAuthorizationStrategy.java
- src/main/resources/com/michelin/cio/hudson/plugins/rolestrategy/RoleStrategyConfig/manage-project-roles.jelly
- src/main/resources/com/michelin/cio/hudson/plugins/rolestrategy/RoleStrategyConfig/manage-roles.jelly
- src/main/webapp/css/role-strategy.css
Remove deprecated jquery-ui dependency. Starting here to figure out what needs to be done next.
> [JENKINS-58536] Remove dependency on deprecated jquery-ui plugin

- src/main/resources/com/michelin/cio/hudson/plugins/rolestrategy/RoleStrategyConfig/manage-roles.jelly
This file has been missed in commit 765e489ab6ee21450c46e8083a4bb3661359eca9.
/CC @oleg-nenashev
> [JENKINS-43058] - Replace obsolete slave/project terms in UI (part 2)

- pom.xml
- src/main/java/com/michelin/cio/hudson/plugins/rolestrategy/RoleMap.java
- src/main/java/com/michelin/cio/hudson/plugins/rolestrategy/RoleStrategyConfig.java
- src/main/java/com/synopsys/arc/jenkins/plugins/rolestrategy/UserMacroExtension.java
- src/main/java/com/synopsys/arc/jenkins/plugins/rolestrategy/macros/StubMacro.java
- src/main/java/org/jenkinsci/plugins/rolestrategy/permissions/PermissionHelper.java
- src/test/java/org/jenkinsci/plugins/rolestrategy/RoleAssignmentTest.java
- src/test/java/org/jenkinsci/plugins/rolestrategy/UserAuthoritiesAsRolesTest.java
Signed-off-by: Raihaan Shouhell <raihaan.shouhell@autodesk.com>
Cleanup old code, remove unused imports.
> Cleanup old code

- pom.xml
- src/main/java/com/michelin/cio/hudson/plugins/rolestrategy/RoleStrategyConfig.java
- src/main/resources/com/michelin/cio/hudson/plugins/rolestrategy/RoleStrategyConfig/assign-global-roles.jelly
- src/main/resources/com/michelin/cio/hudson/plugins/rolestrategy/RoleStrategyConfig/assign-project-roles.jelly
- src/main/resources/com/michelin/cio/hudson/plugins/rolestrategy/RoleStrategyConfig/assign-roles.jelly
- src/main/resources/com/michelin/cio/hudson/plugins/rolestrategy/RoleStrategyConfig/assign-slave-roles.jelly
- src/main/resources/com/michelin/cio/hudson/plugins/rolestrategy/RoleStrategyConfig/index.jelly
- src/main/resources/com/michelin/cio/hudson/plugins/rolestrategy/RoleStrategyConfig/list-macros.jelly
- src/main/resources/com/michelin/cio/hudson/plugins/rolestrategy/RoleStrategyConfig/manage-global-roles.jelly
- src/main/resources/com/michelin/cio/hudson/plugins/rolestrategy/RoleStrategyConfig/manage-project-roles.jelly
- src/main/resources/com/michelin/cio/hudson/plugins/rolestrategy/RoleStrategyConfig/manage-roles.jelly
- src/main/resources/com/michelin/cio/hudson/plugins/rolestrategy/RoleStrategyConfig/manage-slave-roles.jelly
Ref: https://github.com/jenkinsci/jenkins/pull/4524
<details>
<summary>Manage roles</summary>
</details>
<details>
<summary>Assign roles</summary>
</details>
The rest looks the same, are you fine with the extended-read-permission-plugin dep?
> JENKINS-61205 System read support

- README.md
Missed it during the previous scrubs. https://issues.jenkins-ci.org/browse/JENKINS-61302
> [JENKINS-61302] - Remove the bogus "slave" reference in README

- src/main/java/com/michelin/cio/hudson/plugins/rolestrategy/RoleStrategyConfig.java
- src/main/resources/com/michelin/cio/hudson/plugins/rolestrategy/RoleStrategyConfig/assign-roles.jelly
- src/main/resources/com/michelin/cio/hudson/plugins/rolestrategy/RoleStrategyConfig/index.jelly
- src/main/resources/com/michelin/cio/hudson/plugins/rolestrategy/RoleStrategyConfig/manage-roles.jelly
Fixes: https://github.com/jenkinsci/dark-theme/issues/23
Dark:
Light:
> Dark Mode support: Update images to transparent PNGs

- pom.xml
- src/main/java/com/michelin/cio/hudson/plugins/rolestrategy/RoleMap.java
- src/test/java/org/jenkinsci/plugins/rolestrategy/Security2182Test.java
- src/test/resources/org/jenkinsci/plugins/rolestrategy/Security2182Test/config.xml
https://www.jenkins.io/security/advisory/2021-03-18/#SECURITY-2182
Created off a branch because the default branch had unrelated, unreleased commits.
Should be merged using "merge commit" (NOT "squash merge" or "rebase merge") to retain release commits in history.
> Merge 3.1.1 security fix changes into master

- pom.xml
> Use bom to manage dependencies

- README.md
didn't find any code to do this, so write to readme to help more people.
> add code usage for groovy hook script/jenkins script console.

- src/main/java/com/michelin/cio/hudson/plugins/rolestrategy/RoleBasedAuthorizationStrategy.java
- src/test/java/jmh/benchmarks/FolderAccessBenchmark.java
> Remove usage of guava from the plugin

- src/main/java/com/michelin/cio/hudson/plugins/rolestrategy/RoleBasedAuthorizationStrategy.java
/strategy/getMatchingJobs
support utf-8 charset
> Support UTF-8 charset in the /strategy/getMatchingJobs API

- src/main/java/com/michelin/cio/hudson/plugins/rolestrategy/RoleStrategyConfig.java
- src/main/resources/com/michelin/cio/hudson/plugins/rolestrategy/RoleStrategyConfig/assign-roles.jelly
- src/main/resources/com/michelin/cio/hudson/plugins/rolestrategy/RoleStrategyConfig/index.jelly
- src/main/resources/com/michelin/cio/hudson/plugins/rolestrategy/RoleStrategyConfig/list-macros.jelly
- src/main/resources/com/michelin/cio/hudson/plugins/rolestrategy/RoleStrategyConfig/manage-roles.jelly
Preparation for core sunsetting dated icons: `https://github.com/jenkinsci/jenkins/pull/5778`
@oleg-nenashev Would be nice if you can also trigger a release after merging this PR.
Thanks in advance!
> Prepare for sunset icon removal from core

- src/main/java/com/michelin/cio/hudson/plugins/rolestrategy/RoleBasedAuthorizationStrategy.java
- src/main/resources/com/michelin/cio/hudson/plugins/rolestrategy/RoleStrategyConfig/manage-project-roles.jelly
- src/main/resources/com/michelin/cio/hudson/plugins/rolestrategy/RoleStrategyConfig/manage-roles.jelly
- src/main/resources/com/michelin/cio/hudson/plugins/rolestrategy/RoleStrategyConfig/manage-slave-roles.jelly
performs a check of the pattern when the field looses focus
Additionally check when pressing the add button if the pattern is valid to avoid that an invalid pattern can be added at all.
see [JENKINS-67456](https://issues.jenkins.io/browse/JENKINS-67456)
> [JENKINS-67456] add check that pattern is valid

- src/main/resources/com/michelin/cio/hudson/plugins/rolestrategy/RoleStrategyConfig/assign-global-roles.jelly
- src/main/resources/com/michelin/cio/hudson/plugins/rolestrategy/RoleStrategyConfig/assign-project-roles.jelly
- src/main/resources/com/michelin/cio/hudson/plugins/rolestrategy/RoleStrategyConfig/assign-slave-roles.jelly
- src/main/resources/com/michelin/cio/hudson/plugins/rolestrategy/RoleStrategyConfig/manage-global-roles.jelly
- src/main/resources/com/michelin/cio/hudson/plugins/rolestrategy/RoleStrategyConfig/manage-project-roles.jelly
- src/main/resources/com/michelin/cio/hudson/plugins/rolestrategy/RoleStrategyConfig/manage-slave-roles.jelly
[JENKINS-55413](https://issues.jenkins.io/browse/JENKINS-55413)
Newly added lines for all manage and assign roles tables couldn't be
deleted. 
This fixes it.
> [JENKINS-55413] allow to delete newly added lines

- src/main/java/com/michelin/cio/hudson/plugins/rolestrategy/Role.java
avoid binary incompatible change
> revert change to Role

- src/main/resources/com/michelin/cio/hudson/plugins/rolestrategy/RoleStrategyConfig/assign-agent-roles.jelly
- src/main/resources/com/michelin/cio/hudson/plugins/rolestrategy/RoleStrategyConfig/assign-global-roles.jelly
- src/main/resources/com/michelin/cio/hudson/plugins/rolestrategy/RoleStrategyConfig/assign-project-roles.jelly
- src/main/resources/com/michelin/cio/hudson/plugins/rolestrategy/RoleStrategyConfig/assign-roles.jelly
- src/main/resources/com/michelin/cio/hudson/plugins/rolestrategy/RoleStrategyConfig/list-macros.jelly
- src/main/resources/com/michelin/cio/hudson/plugins/rolestrategy/RoleStrategyConfig/manage-agent-roles.jelly
- src/main/resources/com/michelin/cio/hudson/plugins/rolestrategy/RoleStrategyConfig/manage-global-roles.jelly
- src/main/resources/com/michelin/cio/hudson/plugins/rolestrategy/RoleStrategyConfig/manage-project-roles.jelly
- src/main/resources/com/michelin/cio/hudson/plugins/rolestrategy/RoleStrategyConfig/manage-roles.jelly
- src/main/webapp/help/help-pattern.html
replace slave with agent where possible
> Remove offensive language

- src/main/java/com/michelin/cio/hudson/plugins/rolestrategy/RoleBasedAuthorizationStrategy.java
- src/main/java/com/michelin/cio/hudson/plugins/rolestrategy/RoleMap.java
- src/main/resources/com/michelin/cio/hudson/plugins/rolestrategy/RoleStrategyConfig/manage-agent-roles.jelly
- src/main/resources/com/michelin/cio/hudson/plugins/rolestrategy/RoleStrategyConfig/manage-global-roles.jelly
- src/main/resources/com/michelin/cio/hudson/plugins/rolestrategy/RoleStrategyConfig/manage-project-roles.jelly
When clicking on a pattern, the popup now shows the total number of matched items. The number of matched items is still limited to 10.
> [JENKINS-68935] Show total number of matches when pattern matches more than 10 items

- docs/MACROS.md
- pom.xml
- src/main/java/com/synopsys/arc/jenkins/plugins/rolestrategy/macros/FolderMacro.java
- src/main/webapp/css/role-strategy.css
The new macro allows to define a role matching only folders.
> add Folder macro

- src/main/java/org/jenkinsci/plugins/rolestrategy/casc/RoleDefinition.java
Fixed: when a role has no permissions assigned, exporting to Configuration as
code prints an exception inside the output.
> [JENKINS-62124] NPE when exporting role without permissions with casc

- src/main/resources/com/michelin/cio/hudson/plugins/rolestrategy/RoleStrategyConfig/manage-roles.jelly
- src/main/webapp/js/table.js
- src/main/webapp/js/tableManage.js
The pattern shown in the tooltip wasn't updated after changing the
pattern. Instead it showed the pattern that was set at page load or
the value when a new line was added.
> [JENKINS-69101] update tooltip after changing pattern

- src/main/java/com/michelin/cio/hudson/plugins/rolestrategy/RoleBasedAuthorizationStrategy.java
- src/main/resources/com/michelin/cio/hudson/plugins/rolestrategy/RoleStrategyConfig/manage-agent-roles.jelly
- src/main/resources/com/michelin/cio/hudson/plugins/rolestrategy/RoleStrategyConfig/manage-roles.jelly
- src/main/webapp/js/tableManage.js
When a permission is granted that implies other permissions the
checkboxes of these permissions get disabled and the tooltip is updated
accordingly
> [JENKINS-69102] disable implied permissions

- src/main/resources/org/jenkinsci/plugins/rolestrategy/NamingStrategyAdministrativeMonitor/message.jelly
Adopts https://github.com/jenkinsci/jenkins/pull/7364
> Forward compatibility with jenkins-buttons

- .github/dependabot.yml
Closes https://github.com/jenkinsci/role-strategy-plugin/pull/245
> Ban checkstyle updates higher than 10.0

- src/main/java/com/michelin/cio/hudson/plugins/rolestrategy/RoleStrategyConfig.java
- src/main/java/com/synopsys/arc/jenkins/plugins/rolestrategy/macros/ContainedInViewMacro.java
- src/main/java/com/synopsys/arc/jenkins/plugins/rolestrategy/macros/FolderMacro.java
- src/main/java/org/jenkinsci/plugins/rolestrategy/RoleBasedProjectNamingStrategy.java
- src/main/java/org/jenkinsci/plugins/rolestrategy/permissions/PermissionHelper.java
- src/test/java/org/jenkinsci/plugins/rolestrategy/AuthorizeProjectTest.java
Code simplification and other enhancements.
------------------
> Code enhancements

- src/main/resources/com/michelin/cio/hudson/plugins/rolestrategy/RoleStrategyConfig/assign-project-roles.jelly
- src/main/webapp/js/tableAssign.js
there attribute with the initial size was missing for the item table on the assign page, leading to the filters missing
While the user filter showed up when adding a user, the role filter was never shown.
> [JENJKINS-71179] fix filters are missing on assign roles

- README.md
adjust groovy hook script to new user/group separation
```[tasklist]
```
> adjust docu to user/group separation

- src/main/resources/com/michelin/cio/hudson/plugins/rolestrategy/RoleStrategyConfig/assign-agent-roles.jelly
- src/main/resources/com/michelin/cio/hudson/plugins/rolestrategy/RoleStrategyConfig/assign-global-roles.jelly
- src/main/resources/com/michelin/cio/hudson/plugins/rolestrategy/RoleStrategyConfig/assign-project-roles.jelly
- src/main/resources/com/michelin/cio/hudson/plugins/rolestrategy/RoleStrategyConfig/assign-roles.jelly
- src/main/resources/com/michelin/cio/hudson/plugins/rolestrategy/RoleStrategyConfig/index.jelly
- src/main/resources/com/michelin/cio/hudson/plugins/rolestrategy/RoleStrategyConfig/list-macros.jelly
- src/main/resources/com/michelin/cio/hudson/plugins/rolestrategy/RoleStrategyConfig/manage-agent-roles.jelly
- src/main/resources/com/michelin/cio/hudson/plugins/rolestrategy/RoleStrategyConfig/manage-global-roles.jelly
- src/main/resources/com/michelin/cio/hudson/plugins/rolestrategy/RoleStrategyConfig/manage-project-roles.jelly
thead and tfoot are almost identical for global, items and agents. For better maintenance move them to the corresponding taglib and just pass in some variables
```[tasklist]
```
> jelly consolidation

- pom.xml
- src/test/java/org/jenkinsci/plugins/rolestrategy/Security2182Test.java
kill the long running sleep jobs at the end to ensure file handles are closed on windows. Otherwise post test cleanup might fail.
```[tasklist]
```
> stabilize test

- README.md
start an instance  with the given init.groovy script and verified config is applied.
```[tasklist]
```
> [JENKINS-71734] fix documentation

- README.md
- pom.xml
- src/main/java/com/michelin/cio/hudson/plugins/rolestrategy/RoleMap.java
- src/main/java/org/jenkinsci/plugins/rolestrategy/pipeline/AbstractUserRolesStep.java
- src/main/java/org/jenkinsci/plugins/rolestrategy/pipeline/UserGlobalRoles.java
- src/main/java/org/jenkinsci/plugins/rolestrategy/pipeline/UserItemRoles.java
- src/main/resources/org/jenkinsci/plugins/rolestrategy/pipeline/UserGlobalRoles/help.html
- src/main/resources/org/jenkinsci/plugins/rolestrategy/pipeline/UserItemRoles/config.jelly
- src/main/resources/org/jenkinsci/plugins/rolestrategy/pipeline/UserItemRoles/help-showAllRoles.html
- src/main/resources/org/jenkinsci/plugins/rolestrategy/pipeline/UserItemRoles/help.html
- src/test/java/org/jenkinsci/plugins/rolestrategy/pipeline/UserGlobalRolesTest.java
- src/test/java/org/jenkinsci/plugins/rolestrategy/pipeline/UserItemRolesTest.java
- src/test/resources/org/jenkinsci/plugins/rolestrategy/pipeline/Configuration-as-Code-pipeline.yml
added the pipeline steps
currentUserGlobalRoles
currentUserItemRoles
```[tasklist]
```
> [JENKINS-51672][JENKINS-41731] get users role in pipeline

- src/main/resources/com/michelin/cio/hudson/plugins/rolestrategy/RoleStrategyConfig/assign-roles.jelly
- src/main/resources/com/michelin/cio/hudson/plugins/rolestrategy/RoleStrategyConfig/index.jelly
> make delete symbols less prominent

- src/main/java/org/jenkinsci/plugins/rolestrategy/AmbiguousSidsAdminMonitor.java
`mvn clean verify -DskipTests`
> Stop using EOL JSR 305 annotation

- README.md
This PR aims to fix pipeline script call name for Item roles in README
```[tasklist]
- [ x] Please describe what you did
```
> Fix `currentUserItemRoles` pipeline step call name documentation

- Jenkinsfile
remove builds for java11
build windows on java17
> prepare for java17

- pom.xml
- src/main/resources/com/michelin/cio/hudson/plugins/rolestrategy/RoleStrategyConfig/assign-roles.jelly
- src/main/resources/org/jenkinsci/plugins/rolestrategy/AmbiguousSidsAdminMonitor/message.jelly
- src/main/resources/org/jenkinsci/plugins/rolestrategy/NamingStrategyAdministrativeMonitor/message.jelly
> update to 2.479.3

- src/main/webapp/js/tableAssign.js
The bug is reproducible only when there are more than 30 users assigned agent roles.
Clicking on pagination button or selecting the page doesn't display the items of the expected page for agent role assignment.
This is because there are no user input or role input filters.
This issue exists in plugin version `783.ve14e9f60fc26`.
1. Manually tested on browser by updating the changed javascript.
2. Ensure that more than 30 users are assigned agent roles.
3. Go to the assign roles tab "<JENKINS_HOST>/manage/role-strategy/assign-roles"
4. Go to the "Agent roles" section and Click on arrow down button or select the page number from drop down
5. The table must be updated and display the new set of users with their expected agent roles assigned.
> [JENKINS-75848] Fix pagination issue for agent role assignment

- src/main/webapp/css/role-strategy.css
the permission names are not centered
> Align text

- src/main/java/com/michelin/cio/hudson/plugins/rolestrategy/Role.java
the synchronization can lead to too much thread blocking
See JENKINS-75960
> [JENKINS-75960] avoid synchronization in a roles permissions map
